name: Tests and code coverage
on: [push, pull_request]

jobs:
  tests_and_coverage:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        version: [10.x, 12.x, 14.x, 16.x, 18.x]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
      - run: npm ci
      - run: npm test
      - uses: codecov/codecov-action@v3
